import {chromium,expect} from '@playwright/test';
import fs from 'node:fs';
const u=JSON.parse(fs.readFileSync('.backend/test-user.json','utf8'));
const browser=await chromium.launch();const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://localhost:5173/login');await page.getByLabel('Correo electrónico').fill(u.email);await page.getByLabel('Contraseña',{exact:true}).fill(u.password);await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();await expect(page).toHaveURL(/perfil/);await page.getByLabel('Nombre visible').fill('Explorador de prueba');await page.getByRole('button',{name:'Guardar perfil'}).click();await expect(page.getByRole('status')).toContainText('guardado');await page.reload();await expect(page.getByLabel('Nombre visible')).toHaveValue('Explorador de prueba');
await page.goto('http://localhost:5173/admin');await page.getByRole('button',{name:'Nueva versión'}).click();await page.getByLabel('Título',{exact:true}).fill('Publicación de prueba temporal');await page.getByLabel('Versión',{exact:true}).fill('test-e2e');await page.getByLabel('Descripción breve').fill('Prueba temporal de publicación, eliminada al terminar.');await page.getByLabel('Imagen de portada').setInputFiles('public/images/river.png');await page.getByLabel('Contenido de la versión').fill('## Novedades\n\nUna publicación de prueba con imágenes y texto.');await page.getByLabel('Archivos de la versión',{exact:false}).setInputFiles({name:'test-beta.txt',mimeType:'text/plain',buffer:Buffer.from('Integration test, not a game build.')});await page.getByRole('button',{name:'Guardar versión'}).click();await expect(page.getByRole('status').last()).toContainText('Borrador',{timeout:30000});
const anon=await browser.newPage();await anon.goto('http://localhost:5173/descargas');await expect(anon.getByText('Publicación de prueba temporal',{exact:true})).toHaveCount(0);
await page.getByLabel('Visibilidad').selectOption('published');await page.getByRole('button',{name:'Guardar versión'}).click();await expect(page.getByRole('status').last()).toContainText('publicada',{timeout:30000});await anon.reload();await anon.getByRole('link',{name:/Publicación de prueba temporal/}).click();await expect(anon.getByRole('heading',{name:'Publicación de prueba temporal'})).toBeVisible();await expect(anon.getByRole('heading',{name:'Novedades',exact:true})).toBeVisible();const download=anon.getByRole('link',{name:/test-beta.txt/});const response=await anon.request.get(await download.getAttribute('href'));expect(response.status()).toBe(200);expect(await response.text()).toContain('Integration test');
await page.goto('http://localhost:5173/soporte');await page.getByLabel('Título del problema').fill('Bug de prueba desde navegador');await page.getByLabel('¿Qué ocurrió?').fill('Prueba del formulario de soporte desde el navegador.');await page.getByLabel('Pasos para reproducirlo').fill('Abrir el formulario y enviar un reporte de prueba.');await page.getByLabel('Captura opcional',{exact:false}).setInputFiles('public/images/meadow.png');await page.getByRole('button',{name:'Enviar reporte'}).click();await expect(page.getByRole('status')).toContainText('Reporte enviado',{timeout:30000});await page.goto('http://localhost:5173/admin');await page.getByRole('button',{name:'Reportes de bugs'}).click();await expect(page.getByRole('heading',{name:'Bug de prueba desde navegador'})).toBeVisible();const article=page.locator('article').filter({hasText:'Bug de prueba desde navegador'});await article.getByLabel('Estado').selectOption('resolved');await expect(article.getByLabel('Estado')).toHaveValue('resolved');console.log('PASS: login, persisted profile, admin editor, cover upload, draft privacy, publication, real download, bug report, attachment and status update.');console.log('Page errors:',errors);await browser.close();
